hub:
  databaseUrl: postgres://postgres:windmill@windmill-hub-postgresql/windmillhub?sslmode=disable
  appUrl: https://app.mywindmill.dev
  privateHub: "true"
  imageName: ghcr.io/windmill-labs/windmillhub-ee-public:main
  licenseKey: "LICENSE_KEY"
  sslIngress: false
  certArn: arn:aws:acm:us-east-1::myarn
  extraEnv: []
  affinity: {}

postgresql:
  enabled: false
  fullnameOverride: windmill-hub-postgresql
  primary:
    persistence:
      enabled: true
    resources:
      limits:
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "1024Mi"
  auth:
    postgresPassword: windmill
    database: windmillhub
